### ISSUE TITLE
Do not parse the data in llh_publisher

### ISSUE THREAD

**Issue by peci1** [ctu-vras/gps-navigation#4]
https://github.com/ctu-vras/gps-navigation/blob/9a31a020fb8dc5e40f576430022d4ff4ca299723/gps_to_path/nodes/llh_publisher#L42-L42

Let's publish the raw LLH output and do the whole parsing in llh_to_fix.

It'd also be nice to have the sound output in a single node and not spread over both. Or maybe it could even be a standalone node subscribing to `fix` to make it even more generally usable.

**Comment by herolada** [comment]
Raw LLH string is now published.
Created separate sound node.
